// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global Icons {
    out property <image> arrow-up: @image-url("assets/shift.svg");
    out property <image> arrow-left: @image-url("assets/arrow-back.svg");
    out property <image> arrow-right: @image-url("assets/arrow-forward.svg");
    out property <image> chevron-left: @image-url("assets/backspace.svg");
    out property <image> arrow-circle-o-left: @image-url("assets/return.svg");
    out property <image> globe: @image-url("assets/globe.svg");
    out property <image> expand-more: @image-url("assets/double-arrow-down.svg");
    out property <image> tab: @image-url("assets/tab.svg");
}
