// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Button, Palette } from "std-widgets.slint";

import { Icons } from "icons.slint";

component VirtualKeyboardButton {
    in property <string> key;
    in property <image> icon;
    in property <length> key-height;
    in property <length> radius;
    in property <string> font-family;
    in property <float> scaling-factor;

    callback key-pressed(/* key */ string);

    preferred-width: root.key == "" ? key-height * 1.125 : key-height * 0.85;
    min-height: key-height;
    horizontal-stretch: 0;

    i-container := Rectangle {
        background: i-touch-area.pressed ? #000000 : #ffffff;
        border-color: #000000;
        border-width: 2px;
        border-radius: radius;

        HorizontalLayout {
            if (root.key != "") : i-text := Text {
                text: root.key;
                color: i-touch-area.pressed ? #ffffff : #000000;
                font-size: key-height * 0.35 * scaling-factor;
                vertical-alignment: center;
                horizontal-alignment: center;
                font-family: font-family;
                font-weight: 600;
            }

            if (root.key == "") : VerticalLayout {
                alignment: center;
                Image {
                    source: root.icon;
                    height: key-height * 0.5 * scaling-factor;
                    min-width: self.height;
                    colorize: i-touch-area.pressed ? #ffffff : #000000;
                }
            }
        }
    }

    i-state-area := Rectangle {
        border-radius: i-container.border-radius;
        opacity: 0;
        background: #000000;
    }

    i-touch-area := TouchArea {
        pointer-event(event) => {
            if(event.kind == PointerEventKind.down) {
                root.key-pressed(key);
            }
        }
    }
}

export struct KeyModel {
    key: string,
    shift-key: string,
}

export global VirtualKeyboardHandler {
    in property <[[[KeyModel]]]> default-key-sets: [
       [
            [
                { key: "q", shift-key: "Q" },
                { key: "w", shift-key: "W"  },
                { key: "e", shift-key: "E"  },
                { key: "r", shift-key: "R"  },
                { key: "t", shift-key: "T"  },
                { key: "y", shift-key: "Y"  },
                { key: "u", shift-key: "U"  },
                { key: "i", shift-key: "I"  },
                { key: "o", shift-key: "O"  },
                { key: "p", shift-key: "P"  }
            ],
            [
                { key: "a", shift-key: "A" },
                { key: "s", shift-key: "S" },
                { key: "d", shift-key: "D" },
                { key: "f", shift-key: "F" },
                { key: "g", shift-key: "G" },
                { key: "h", shift-key: "H" },
                { key: "j", shift-key: "J" },
                { key: "k", shift-key: "K" },
                { key: "l", shift-key: "L" }
            ],
            [
                { key: "z", shift-key: "Z" },
                { key: "x", shift-key: "X" },
                { key: "c", shift-key: "C" },
                { key: "v", shift-key: "V" },
                { key: "b", shift-key: "B" },
                { key: "n", shift-key: "N" },
                { key: "m", shift-key: "M" },
                { key: ",", shift-key: ";" },
                { key: ".", shift-key: ":" },
                { key: "?", shift-key: "?" }
            ],
       ],
       [
            [
                { key: "1", shift-key: "[" },
                { key: "2", shift-key: "]" },
                { key: "3", shift-key: "{" },
                { key: "4", shift-key: "}" },
                { key: "5", shift-key: "#" },
                { key: "6", shift-key: "%" },
                { key: "7", shift-key: "^" },
                { key: "8", shift-key: "*" },
                { key: "9", shift-key: "+" },
                { key: "0", shift-key: "=" }
            ],
            [
                { key: "-", shift-key: "_" },
                { key: "/", shift-key: "\\" },
                { key: ":", shift-key: "|" },
                { key: ";", shift-key: "~" },
                { key: "(", shift-key: "<" },
                { key: ")", shift-key: ">" },
                { key: "€", shift-key: "$" },
                { key: "&", shift-key: "€" },
                { key: "@", shift-key: "°" },
                { key: "'", shift-key: "#" },
            ],
            [
                { key: ".", shift-key: "." },
                { key: ",", shift-key: "," },
                { key: "?", shift-key: "?" },
                { key: "!", shift-key: "!" },
                { key: "'", shift-key: "'" },
            ],
       ]
    ];

    in-out property <int> current-key-set;
    out property <[[KeyModel]]> keys: default-key-sets[self.current-key-set];
    in-out property <bool> open;

    callback key_pressed(/* key */ string);

    public function switch-keyboard() {
        if (self.current-key-set < self.default-key-sets.length - 1) {
            self.current-key-set += 1;
        } else {
            self.current-key-set -= 1;
        }

        self.current-key-set = min(self.default-key-sets.length - 1, max(0, self.current-key-set))
    }
}

export component VirtualKeyboard {
    in-out property <bool> shift;
    in property <length> key-height;
    in property <length> radius;
    in property <string> font-family;
    in property <float> scaling-factor;

    callback close();

    preferred-width: 100%;

    TouchArea {}

    Rectangle {
        border-width: 3px;
        border-color: black;
        background: #000000;
        height: 100%;
    }

    i-layout := VerticalLayout {
        padding: 30px;
        spacing: 8px;

        for row[index] in VirtualKeyboardHandler.keys : HorizontalLayout {
            spacing: 8px;
            if (index == 0) : VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                key: "⎋";
            }

            if (index == 1) : VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.tab;

                key-pressed => {
                    VirtualKeyboardHandler.key-pressed(Key.Tab);
                }
            }

            // shift
            if (index == 2) : VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.arrow-up;

                key-pressed => {
                    root.shift = !root.shift;
                }
            }

            for km in row : VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                key: root.shift ? km.shift-key : km.key;

                key-pressed(key) => {
                    VirtualKeyboardHandler.key-pressed(key);
                    root.shift = false;
                }
            }

            if (index == 0) : VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.chevron-left;

                key-pressed => {
                    VirtualKeyboardHandler.key-pressed(Key.Backspace);
                }
            }

            if (index == 1) : VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.arrow-circle-o-left;

                key-pressed => {
                    VirtualKeyboardHandler.key-pressed(Key.Return);
                }
            }

            // shift
            if (index == 2) : VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.arrow-up;

                key-pressed => {
                    root.shift = !root.shift;
                }
            }
        }

        HorizontalLayout {
            spacing: 8px;

             VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.expand-more;

                key-pressed(key) => {
                    root.close();
                }
            }

            VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.globe;

                key-pressed(key) => {
                    VirtualKeyboardHandler.switch-keyboard();
                }
            }
            VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                horizontal-stretch: 10;
                key: " ";

                key-pressed(key) => {
                    root.shift = false;
                    VirtualKeyboardHandler.key-pressed(key);
                }
            }
            VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.arrow-left;

                key-pressed(key) => {
                    VirtualKeyboardHandler.key-pressed(Key.LeftArrow);
                }
            }
            VirtualKeyboardButton {
                key-height: key-height;
                font-family: font-family;
                scaling-factor: scaling-factor;
                radius: radius;
                icon: Icons.arrow-right;

                key-pressed(key) => {
                    VirtualKeyboardHandler.key-pressed(Key.RightArrow);
                }
            }
        }
    }
}
