[workspace]
resolver = "2"
members = ["qinit", "libqinit"]

[patch.crates-io]
slint = { git = "https://github.com/PorQ-Pine/slint-package.git" }

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
