[package]
name = "quill-init"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
crossterm = "0.29.0"
env_logger = "0.11.8"
log = "0.4.27"
network-interface = "2.0.1"
openssl = "0.10.73"

[features]
debug = []
