export component Button inherits TouchArea {
    in property<string> text <=> i-text.text;
    in property<length> border-radius <=> i-container.border-radius;

    i-container := Rectangle {
        border-width: 3px;
        border-color: #000000;
        background: #f0f0f0;

        HorizontalLayout {  
            padding: 4px;

            i-text := Text {
                color: #000000;
                horizontal-alignment: center;
                vertical-alignment: center;
                font-family: "Inter";
                font-weight: 800;
            }
        }
    }

    states [  
        pressed when root.pressed: {
            i-container.background: #000000;
            i-text.color: #ffffff;
        }
    ]
}
