import { Button } from "button.slint";
export component Dialog inherits Rectangle {
    in property <string> text <=> i-text.text;
    in property <string> button_font_family;
    property <length> button_height: root.height * 0.15;
    callback cancel();
    callback confirm();

    border-color: black;
    border-width: 6px;
    background: white;

    TouchArea {
        width: parent.width;
        height: parent.height;
        enabled: true;
    }
    VerticalLayout {
        padding: 40px;
        Rectangle {}
        i-text := Text {
            horizontal-alignment: center;
            wrap: word-wrap;
        }
        Rectangle {}
        HorizontalLayout {
            spacing: 30px;
            Button {
                text: "Cancel";
                height: button_height;
                border-radius: root.border-radius;
                font-family: button_font_family;
                clicked => {
                    cancel();
                }
            }
            Button {
                text: "Confirm";
                height: button_height;
                border-radius: root.border-radius;
                font-family: button_font_family;
                clicked => {
                    confirm();
                }
            }
        }
    }
}
