export component HLine inherits VerticalLayout {
    in property <float> top-padding-multiplier: 1;
    in property <float> bottom-padding-multiplier: 1;
    in property <length> thickness: 3px;
    in property <brush> background <=> i-container.background;
    padding-top: 5px * top-padding-multiplier;
    padding-bottom: 5px * bottom-padding-multiplier;
    i-container := Rectangle {
        background: black;
        height: thickness;
    }
}
