export component IconButton inherits TouchArea {
    in property<image> icon <=> i-icon.source;
    in property<length> border-radius <=> i-container.border-radius;
    in property<length> padding-value;

    i-container := Rectangle {
        background: #f0f0f0;

        i-layout := HorizontalLayout {
            padding: padding-value;
            i-icon := Image { }
        }
    }

    states [  
        pressed when root.pressed: {
            i-container.background: #000000;
        }
    ]
}
