import { Properties as P } from "properties.slint";

export component IconButton inherits TouchArea {
    in property <image> icon <=> i-icon.source;
    in property <length> border-radius <=> i-container.border-radius;
    in property <length> padding-value;
    in property <color> background-color;

    i-container := Rectangle {
        background: background-color;

        i-layout := HorizontalLayout {
            padding: padding-value;
            i-icon := Image {
                colorize: root.enabled ? (i-container.background == #000000 ? #ffffff : #000000) : P.item-disabled-color;
            }
        }
    }

    states [  
        pressed when root.pressed: {
            i-container.background: #000000;
        }
    ]
}
