export component MinorButton inherits TouchArea {
    in property <string> text <=> i-text.text;
    in property <string> font-family <=> i-text.font-family;
    in property <int> font-weight <=> i-text.font-weight;

    i-container := Rectangle {
        border-radius: 10px;
        border-color: #000000;
        background: #ffffff;

        HorizontalLayout {  
            padding: 4px;

            i-text := Text {
                color: #000000;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }
    }

    states [  
        pressed when root.pressed: {
            i-container.background: #000000;
            i-text.color: #ffffff;
        }
    ]
}
