export component SectionButton inherits TouchArea {
    in property <string> text <=> i-text.text;
    in property <length> border-radius <=> i-container.border-radius;
    in property <string> font-family <=> i-text.font-family;
    in property <length> font-size <=> i-text.font-size;
    in property <image> icon <=> i-icon.source;
    in property <float> scaling-factor;

    i-container := Rectangle {
        background: #dbdada;

        HorizontalLayout {
            padding-left: scaling-factor > 1 ? 15px : 27.5px;
            spacing: scaling-factor > 1 ? 5px : 21px;

            i-icon := Image {
                height: parent.height * 0.6;
                width: self.height;
                y: (parent.height - self.height) / 2;
                colorize: i-container.background == #000000 ? #ffffff : #000000;
            }

            i-text := Text {
                color: #000000;
                vertical-alignment: center;
                font-weight: 800;
            }

            Rectangle { }

            Image {
                source: @image-url("../icons/chevron-right.svg");
                height: parent.height * 0.8;
                width: self.height;
                y: (parent.height - self.height) / 2;
                colorize: i-container.background == #000000 ? #ffffff : #000000;
            }
        }
    }

    states [  
        pressed when root.pressed: {
            i-container.background: #000000;
            i-text.color: #ffffff;
        }
    ]
}
