export component SectionButton inherits TouchArea {
    in property <string> text <=> i-text.text;
    in property <length> border-radius <=> i-container.border-radius;
    in property <string> font-family <=> i-text.font-family;
    in property <image> icon <=> i-icon.source;

    i-container := Rectangle {
        background: #dbdada;

        HorizontalLayout {  
            padding-left: 27.5px;
            spacing: 21px;

            i-icon := Image {
                height: parent.height * 0.6;
                width: self.height;
                y: (parent.height - self.height) / 2;
            }

            i-text := Text {
                color: #000000;
                vertical-alignment: center;
                font-weight: 800;
            }

            Rectangle { }

            Image {
                source: @image-url("../icons/chevron-right.svg");
                height: parent.height * 0.8;
                width: self.height;
                y: (parent.height - self.height) / 2;
            }
        }
    }

    states [  
        pressed when root.pressed: {
            i-container.background: #000000;
            i-text.color: #ffffff;
        }
    ]
}
