import { Properties as P } from "properties.slint";

export component Switch {
    in property <length> border-radius <=> i-container.border-radius;
    in-out property <bool> activated;
    in-out property <bool> enabled <=> touch-area.enabled;
    in-out property <bool> special-activation;
    property<float> handle_width_multiplier: 0.85;
    property<float> handle_height_multiplier: 0.8 * handle_width_multiplier;
    callback toggled;

    touch-area := TouchArea {
        i-container := Rectangle {
            border-width: 3px;
            border-color: enabled ? #000000 : P.item-disabled-color;
            background: enabled ? #000000 : P.item-disabled-color;
            Rectangle {
                border-radius: parent.border-radius;
                width: parent.width * handle_width_multiplier;
                height: parent.height * handle_height_multiplier;
                Rectangle {
                    width: parent.width * 0.5;
                    x: activated ? parent.width * 0.5 : 0;
                    border-radius: parent.border-radius;
                    border-width: 3px;
                    border-color: enabled ? #000000 : P.item-disabled-color;
                    background: #ffffff;
                }
            }
        }
        clicked => {
            if !special-activation {
                activated = !activated;
            }
            toggled();
        }
    }
}
