import { ProgressBar } from "../../ui-common/progressbar.slint";
import { Button } from "../../ui-common/button.slint";
import { MinorButton } from "../../ui-common/minorbutton.slint";

export enum Page { None, QuillBoot, VersionInfo, BootSplash }
export enum Dialog { None, Toast, ConfirmationDialog }

export component AppWindow inherits Window {
    default-font-family: "U001";
    default-font-size: 40px;

    // Callbacks
    callback power_off();

    in-out property<string> version_string;
    in-out property<float> boot_progress;
    in-out property<Page> page;
    in-out property<Dialog> dialog;
    in-out property<string> dialog_message;
    in-out property<int> dialog_millis_count;
    // Generic multipliers for default-sized and smaller-sized buttons
    property<float> wmultiplier: 0.25;
    property<float> hmultiplier: 0.05;
    property<float> swmultiplier: 0.25;
    property<float> shmultiplier: 0.03;
    // Sizes
    property<int> header_font_size: 80;
    property<int> layout_padding: 60;

    // Main UI
    if (page == Page.QuillBoot) : VerticalLayout {
        padding: layout_padding * 1px;
        Rectangle {}
        HorizontalLayout {
            alignment: center;
            Image {
                // Displaying the same image but with the SVG file gave terrible results, for some reason
                source: @image-url("../../branding/quill-banner.png");
                width: 768px;
                height: 330.5625px;
            }
        }
        Rectangle {}
        HorizontalLayout {
            Text {
                text: "QuillBoot";
                horizontal-alignment: center;
                font-family: "Inter";
                font-size: header_font_size * 1px;
                font-weight: 800;
            }
        }
        HorizontalLayout {
            alignment: center;
            Text {
                text: "Diagnostics & Recovery";
                font-size: 40px;
            }
        }
        Rectangle {}
        HorizontalLayout {
            Rectangle {}
            Button {
                text: "Recovery GUI";
                width: root.width * wmultiplier;
                height: root.height * hmultiplier;
            }
            Rectangle {}
            Button {
                text: "Quill OS";
                width: root.width * wmultiplier;
                height: root.height * hmultiplier;
            }
            Rectangle {}
            Button {
                text: "Power off";
                width: root.width * wmultiplier;
                height: root.height * hmultiplier;
                clicked => {
                    root.power_off();
                }
            }
            Rectangle {}
        }
        Rectangle {}
        HorizontalLayout {
            alignment: center;
            Button {
                text: "Device details";
                width: root.width * wmultiplier;
                height: root.height * hmultiplier;
                clicked => {
                    root.page = Page.VersionInfo;
                }
            }
        }
    }

    if (page == Page.BootSplash) : VerticalLayout {
        Rectangle {}
        HorizontalLayout {
            alignment: center;
            Image {
                source: @image-url("../../branding/quillos.svg");
                width: 45%;
                height: 45%;
            }
        }

        HorizontalLayout {
            alignment: center;
            ProgressBar {
                progress: root.boot_progress;
                width: 37.5%;
                height: 2%;
            }
        }
        Rectangle {}
    }

    if (page == Page.VersionInfo) : VerticalLayout {
        VerticalLayout{
            padding: layout_padding * 1px;
            Rectangle {}
            HorizontalLayout {
                alignment: center;
                Image {
                    source: @image-url("../../branding/quillos.svg");
                    width: 25%;
                    height: 25%;
                }
            }
            Rectangle { vertical-stretch: 0.25; }
            Text {
                text: "Copyright © 2021-2025";
                horizontal-alignment: center;
                font-family: "Inter";
                font-weight: 800;
            }
            Text {
                text: "Nicolas Mailloux <nicolecrivain@gmail.com>\nSzybet <https://github.com/Szybet>";
                horizontal-alignment: center;
            }
            Rectangle {}
            Text {
                text: root.version_string;
                horizontal-alignment: center;
                wrap: word-wrap;
            }
            Rectangle {}
            HorizontalLayout{
                alignment: center;
                Button {
                    text: "Back";
                    width: root.width * wmultiplier;
                    height: root.height * hmultiplier;
                    clicked => {
                        root.page = Page.QuillBoot;
                    }
                }
            }
        }
    }

    // Toast/dialogs
    if (dialog == Dialog.Toast) : Rectangle {
        width: 40%;
        height: 7%;
        x: (parent.width - self.width) / 2; y: (parent.height - self.height) / 2;
        border-color: black;
        border-width: 6px;
        border-radius: 10px;
        background: white;
        Text {
            text: root.dialog_message;
            font-family: "Inter";
            font-weight: 800;
        }
    }
}
